[project]
name = "aoc2024"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jax>=0.4.35",
    "matplotlib>=3.10.0",
    "scikit-learn>=1.6.0",
]
